### ISSUE TITLE
Decryption error

### ISSUE THREAD

**Issue by bugushe** [WHTJEON/widevine-dl#1]
![KS5N87(W O}X9`YH~AK_`PV](https://user-images.githubusercontent.com/54765822/115364196-b921ed80-a1f5-11eb-87be-984e850ff6d5.png)
The key right, but Decryption error

**Comment by WHTJEON** [comment]
What exactly did you input for the key value? Did you follow the format mentioned in the Readme file?

**Comment by bugushe** [comment]
> 您究竟输入了什么作为键值？您是否遵循自述文件中提到的格式？

it's like this  WidevineDecryptor: Found key:  ad925fe4805be12fa11fd38a57cf1daa (KID=071120ce5283c021cf7b4527d8efc91f)
sorry,My english is very bad

**Comment by bugushe** [comment]
> What exactly did you input for the key value? Did you follow the format mentioned in the Readme file?

it's like this WidevineDecryptor: Found key: ad925fe4805be12fa11fd38a57cf1daa (KID=071120ce5283c021cf7b4527d8efc91f)
sorry,My english is very bad

**Comment by WHTJEON** [comment]
Try one more time using EXACTLY 
WidevineDecryptor: Found key: ad925fe4805be12fa11fd38a57cf1daa (KID=071120ce5283c021cf7b4527d8efc91f)
as the input. If the problem continues, I will provide an update. Also, it would be better if you can provide the mpd link

**Comment by bugushe** [comment]
> Try one more time using EXACTLY
> `WidevineDecryptor: Found key: ad925fe4805be12fa11fd38a57cf1daa (KID=071120ce5283c021cf7b4527d8efc91f)`
> as the input. If the problem continues, I will provide an update. Also, it would be better if you can provide the mpd link

Still fail，and the link https://theater.kktv.com.tw/26/03000626010002_898794044276d434d3842734bee064ff/1617455638a10599a69b_dash.playback_p3.mpd
![image](https://user-images.githubusercontent.com/54765822/115477180-f29a3d80-a275-11eb-90f6-ce3288864446.png)
![image](https://user-images.githubusercontent.com/54765822/115477214-047be080-a276-11eb-8c94-cde83c8f35fd.png)

**Comment by WHTJEON** [comment]
I tested with your MPD file and it works fine. I successfully downloaded the content. It seems that you have an extra blank space somewhere in the widevine prompt. You can test it again by copying `WidevineDecryptor: Found key: ad925fe4805be12fa11fd38a57cf1daa (KID=071120ce5283c021cf7b4527d8efc91f)` instead of copying directly from your extension. By the way, I will push an update by the end of this week so you can wait until then if it doesn’t work again.

**Comment by bugushe** [comment]
> I tested with your MPD file and it works fine. I successfully downloaded the content. It seems that you have an extra blank space somewhere in the widevine prompt. You can test it again by copying `WidevineDecryptor: Found key: ad925fe4805be12fa11fd38a57cf1daa (KID=071120ce5283c021cf7b4527d8efc91f)` instead of copying directly from your extension. By the way, I will push an update by the end of this week with a better process of parsing the key so you can wait until then if it doesn’t work again.

thanks，I'll try it

**Comment by bugushe** [comment]
> I tested with your MPD file and it works fine. I successfully downloaded the content. It seems that you have an extra blank space somewhere in the widevine prompt. You can test it again by copying `WidevineDecryptor: Found key: ad925fe4805be12fa11fd38a57cf1daa (KID=071120ce5283c021cf7b4527d8efc91f)` instead of copying directly from your extension. By the way, I will push an update by the end of this week with a better process of parsing the key so you can wait until then if it doesn’t work again.

Hi,guy! like this ,there have three key or two key ,It's can working?
![image](https://user-images.githubusercontent.com/54765822/115541678-01aed900-a2d2-11eb-8143-474612ec7ebc.png)

**Comment by WHTJEON** [comment]
Can

> > I tested with your MPD file and it works fine. I successfully downloaded the content. It seems that you have an extra blank space somewhere in the widevine prompt. You can test it again by copying `WidevineDecryptor: Found key: ad925fe4805be12fa11fd38a57cf1daa (KID=071120ce5283c021cf7b4527d8efc91f)` instead of copying directly from your extension. By the way, I will push an update by the end of this week with a better process of parsing the key so you can wait until then if it doesn’t work again.
> 
> Hi,guy! like this ,there have three key or two key ,It's can working?
> ![image](https://user-images.githubusercontent.com/54765822/115541678-01aed900-a2d2-11eb-8143-474612ec7ebc.png)

Can you send me the mpd link? I will test it and if it works with only one key, I will let you know. If it doesn't, I will push an update this weekend to support multiple keys.

**Comment by bugushe** [comment]
> > > I tested with your MPD file and it works fine. I successfully downloaded the content. It seems that you have an extra blank space somewhere in the widevine prompt. You can test it again by copying `WidevineDecryptor: Found key: ad925fe4805be12fa11fd38a57cf1daa (KID=071120ce5283c021cf7b4527d8efc91f)` instead of copying directly from your extension. By the way, I will push an update by the end of this week with a better process of parsing the key so you can wait until then if it doesn’t work again.
> > 
> > 
> > Hi,guy! like this ,there have three key or two key ,It's can working?
> > ![image](https://user-images.githubusercontent.com/54765822/115541678-01aed900-a2d2-11eb-8143-474612ec7ebc.png)
> 
> Can you send me the mpd link? I will test it and if it works with only one key, I will let you know. If it doesn't, I will push an update this weekend to support multiple keys.
https://bitmovin.com/demos/drm

**Comment by WHTJEON** [comment]
> > > > I tested with your MPD file and it works fine. I successfully downloaded the content. It seems that you have an extra blank space somewhere in the widevine prompt. You can test it again by copying `WidevineDecryptor: Found key: ad925fe4805be12fa11fd38a57cf1daa (KID=071120ce5283c021cf7b4527d8efc91f)` instead of copying directly from your extension. By the way, I will push an update by the end of this week with a better process of parsing the key so you can wait until then if it doesn’t work again.
> > > 
> > > 
> > > Hi,guy! like this ,there have three key or two key ,It's can working?
> > > ![image](https://user-images.githubusercontent.com/54765822/115541678-01aed900-a2d2-11eb-8143-474612ec7ebc.png)
> > 
> > 
> > Can you send me the mpd link? I will test it and if it works with only one key, I will let you know. If it doesn't, I will push an update this weekend to support multiple keys.
> > https://bitmovin.com/demos/drm

Use the first key. The other keys are not working.

**Comment by bugushe** [comment]
> > > > > I tested with your MPD file and it works fine. I successfully downloaded the content. It seems that you have an extra blank space somewhere in the widevine prompt. You can test it again by copying `WidevineDecryptor: Found key: ad925fe4805be12fa11fd38a57cf1daa (KID=071120ce5283c021cf7b4527d8efc91f)` instead of copying directly from your extension. By the way, I will push an update by the end of this week with a better process of parsing the key so you can wait until then if it doesn’t work again.
> > > > 
> > > > 
> > > > Hi,guy! like this ,there have three key or two key ,It's can working?
> > > > ![image](https://user-images.githubusercontent.com/54765822/115541678-01aed900-a2d2-11eb-8143-474612ec7ebc.png)
> > > 
> > > 
> > > Can you send me the mpd link? I will test it and if it works with only one key, I will let you know. If it doesn't, I will push an update this weekend to support multiple keys.
> > > https://bitmovin.com/demos/drm
> 
> Use the first key. The other keys are not working.

But some web video have a key , Audio have another key

**Comment by WHTJEON** [comment]
> > > > > > I tested with your MPD file and it works fine. I successfully downloaded the content. It seems that you have an extra blank space somewhere in the widevine prompt. You can test it again by copying `WidevineDecryptor: Found key: ad925fe4805be12fa11fd38a57cf1daa (KID=071120ce5283c021cf7b4527d8efc91f)` instead of copying directly from your extension. By the way, I will push an update by the end of this week with a better process of parsing the key so you can wait until then if it doesn’t work again.
> > > > > 
> > > > > 
> > > > > Hi,guy! like this ,there have three key or two key ,It's can working?
> > > > > ![image](https://user-images.githubusercontent.com/54765822/115541678-01aed900-a2d2-11eb-8143-474612ec7ebc.png)
> > > > 
> > > > 
> > > > Can you send me the mpd link? I will test it and if it works with only one key, I will let you know. If it doesn't, I will push an update this weekend to support multiple keys.
> > > > https://bitmovin.com/demos/drm
> > 
> > 
> > Use the first key. The other keys are not working.
> 
> But some web video have a key , Audio have another key

Can you provide any specific mpd links for it? I would need them to test and provide a new update

**Comment by bugushe** [comment]
> > > > > > > I tested with your MPD file and it works fine. I successfully downloaded the content. It seems that you have an extra blank space somewhere in the widevine prompt. You can test it again by copying `WidevineDecryptor: Found key: ad925fe4805be12fa11fd38a57cf1daa (KID=071120ce5283c021cf7b4527d8efc91f)` instead of copying directly from your extension. By the way, I will push an update by the end of this week with a better process of parsing the key so you can wait until then if it doesn’t work again.
> > > > > > 
> > > > > > 
> > > > > > Hi,guy! like this ,there have three key or two key ,It's can working?
> > > > > > ![image](https://user-images.githubusercontent.com/54765822/115541678-01aed900-a2d2-11eb-8143-474612ec7ebc.png)
> > > > > 
> > > > > 
> > > > > Can you send me the mpd link? I will test it and if it works with only one key, I will let you know. If it doesn't, I will push an update this weekend to support multiple keys.
> > > > > https://bitmovin.com/demos/drm
> > > 
> > > 
> > > Use the first key. The other keys are not working.
> > 
> > 
> > But some web video have a key , Audio have another key
> 
> Can you provide any specific mpd links for it? I would need them to test and provide a new update

sorry,I know the web like HBO Amazon,but i no account。 https://v.qq.com/x/cover/gk11svuomdpsgl4/f0027zr3wyu.html,the web doesn't mpd links.

**Comment by WHTJEON** [comment]
> > > > > > > > I tested with your MPD file and it works fine. I successfully downloaded the content. It seems that you have an extra blank space somewhere in the widevine prompt. You can test it again by copying `WidevineDecryptor: Found key: ad925fe4805be12fa11fd38a57cf1daa (KID=071120ce5283c021cf7b4527d8efc91f)` instead of copying directly from your extension. By the way, I will push an update by the end of this week with a better process of parsing the key so you can wait until then if it doesn’t work again.
> 
> > > > > > > 
> 
> > > > > > > 
> 
> > > > > > > Hi,guy! like this ,there have three key or two key ,It's can working?
> 
> > > > > > > ![image](https://user-images.githubusercontent.com/54765822/115541678-01aed900-a2d2-11eb-8143-474612ec7ebc.png)
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > Can you send me the mpd link? I will test it and if it works with only one key, I will let you know. If it doesn't, I will push an update this weekend to support multiple keys.
> 
> > > > > > https://bitmovin.com/demos/drm
> 
> > > > 
> 
> > > > 
> 
> > > > Use the first key. The other keys are not working.
> 
> > > 
> 
> > > 
> 
> > > But some web video have a key , Audio have another key
> 
> > 
> 
> > Can you provide any specific mpd links for it? I would need them to test and provide a new update
> 
> 
> 
> sorry,I know the web like HBO Amazon,but i no account。 https://v.qq.com/x/cover/gk11svuomdpsgl4/f0027zr3wyu.html,the web doesn't mpd links.

I will not provide any support for downloading paid content from a paid subscription.
