### ISSUE TITLE
ffmpeg -i %s/decrypted_video.mp4 -i %s/decrypted_audio.m4a -c:v copy -c:a copy %s/%s'%

### ISSUE THREAD

**Issue by lehieucamau** [WHTJEON/widevine-dl#2]
Hi, came to ffmpeg -i to join video and audio but failed, error it as described above, thanks for your instructions. 
![8](https://user-images.githubusercontent.com/22044351/117271541-7cf0bd00-ae84-11eb-91ca-69f474087c15.png)

**Comment by WHTJEON** [comment]
Create a blank output folder in the widevine-dl directory. That will do the fix. If it doesn't let me know.

**Comment by lehieucamau** [comment]
![01](https://user-images.githubusercontent.com/22044351/117293649-ddd7bf80-ae9b-11eb-8259-3862b5f19914.png)
![02](https://user-images.githubusercontent.com/22044351/117293658-dfa18300-ae9b-11eb-8efc-b102ada8688d.png)
![03](https://user-images.githubusercontent.com/22044351/117293662-e0d2b000-ae9b-11eb-8e55-92318ded5955.png)
How do I make ffmpeg to merge video and audio?

**Comment by lehieucamau** [comment]
![04](https://user-images.githubusercontent.com/22044351/117294296-ae758280-ae9c-11eb-8c3c-90781697d379.png)
I created a new folder called Test but it still doesn't work

**Comment by WHTJEON** [comment]
You should include the extension in the file name input. For example, input 'final.mp4' not just 'final'

**Comment by lehieucamau** [comment]
great thanks you much for the good run

**Comment by fijo33** [comment]
> 
> 
> You should include the extension in the file name input. For example, input 'final.mp4' not just 'final'

if that's really your method you should delete it
you make people waste time 

those who want to decrypt their videos
send mp rikottechan@gmail.com
I only sell the method it is not free

**Comment by WHTJEON** [comment]
> > You should include the extension in the file name input. For example, input 'final.mp4' not just 'final'
> 
> if that's really your method you should delete it
> you make people waste time
> 
> those who want to decrypt their videos
> send mp [rikottechan@gmail.com](mailto:rikottechan@gmail.com)
> I only sell the method it is not free

There are a lot of people who wishes to output the file in a desired format including mkv, mts, and etc. That's why I made people input the extension as well. Thus, do not try to sell your scam methods in other people's repos.

**Comment by fijo33** [comment]
.....................
I sell what I want, it is not his property
